package modelo;
// Generated 14 dic 2023 18:54:12 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes implements java.io.Serializable {

	private int id;
	private String nombre;
	private String ape1;
	private String ape2;
	private byte[] esFrecuente;
	private String telefono;
	private String direccionPostal;
	private String nif;
	private String email;
	

	public Clientes() {
	}

	public Clientes(int id, String nombre, String ape1, String ape2, byte[] esFrecuente, String telefono,
			String direccionPostal, String nif, String email) {
		this.id = id;
		this.nombre = nombre;
		this.ape1 = ape1;
		this.ape2 = ape2;
		this.esFrecuente = esFrecuente;
		this.telefono = telefono;
		this.direccionPostal = direccionPostal;
		this.nif = nif;
		this.email = email;
		
		
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApe1() {
		return this.ape1;
	}

	public void setApe1(String ape1) {
		this.ape1 = ape1;
	}

	public String getApe2() {
		return this.ape2;
	}

	public void setApe2(String ape2) {
		this.ape2 = ape2;
	}

	public byte[] getEsFrecuente() {
		return this.esFrecuente;
	}

	public void setEsFrecuente(byte[] esFrecuente) {
		this.esFrecuente = esFrecuente;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getDireccionPostal() {
		return this.direccionPostal;
	}

	public void setDireccionPostal(String direccionPostal) {
		this.direccionPostal = direccionPostal;
	}

	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	

	

	

}
