package modelo;
// Generated 14 dic 2023 18:54:12 by Hibernate Tools 6.3.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos implements java.io.Serializable {

	private int id;
	
	private String nombre;
	private String descripcion;
	private int precio;
	private int stock;
	private Date fecha_alta;
	

	public Productos() {
	}

	public Productos(int id,  String nombre, String descripcion, int precio, int stock, Date fecha_alta) {
		this.id = id;
		this.fecha_alta = fecha_alta;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.precio = precio;
		this.stock = stock;
		
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	public Date getfecha_alta() {
		return this.fecha_alta;
	}

	public void setfecha_alta(Date fecha) {
		this.fecha_alta = fecha;
	}

	

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public int getPrecio() {
		return this.precio;
	}

	public void setPrecio(int precio) {
		this.precio = precio;
	}

	public int getStock() {
		return this.stock;
	}

	public void setStock(int stock) {
		this.stock = stock;
	}

	

}
