package modelo;
// Generated 14 dic 2023 18:54:12 by Hibernate Tools 6.3.1.Final

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private int id;
	
	private String nombre;
	private String password;
	private String email;
	private boolean terminosuso;
	private Integer permiso;
	private boolean contrasenagenerada;

	public Usuarios() {
	}

	public Usuarios(int id,String nombre, String password, String email, boolean terminosuso,Integer permiso, boolean contrasenagenerada) {
		
		this.nombre = nombre;
		this.password = password;
		this.email = email;
		this.terminosuso = terminosuso;
		this.permiso = permiso;
		this.contrasenagenerada= contrasenagenerada;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	

	

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public boolean getTerminosuso() {
		return this.terminosuso;
	}

	public void setTerminosuso(boolean terminosuso) {
		this.terminosuso = terminosuso;
	}

	public Integer getPermiso() {
		return this.permiso;
	}

	public void setPermiso(Integer permiso) {
		this.permiso = permiso;
	}
	public void setContrasenagenerada(Boolean bandera) {
		this.contrasenagenerada = bandera;
	}
	
	public boolean getContrasenagenerada() {
		return this.contrasenagenerada;
	}
	
	

}
